Feat/account page
Hemazyn/WillBeThere-RSVP pull request #6
Opened 2024-04-24 07:56 UTC by ezeaniiandrew

Updated the UI:
- Added card menu and used the appropriate icon for the cards

2024-04-24 08:04 UTC, Hemazyn approved these changes
Good job.

2024-04-25 11:41 UTC, Leeyah-123 approved these changes

2024-04-25 11:41 UTC, Leeyah-123 commented on src/pages/Browse/index.jsx
> +                    <EventCardIcon onClick={() => setIsBookmarked(!isBookmarked)}>
Move all this into the event card itself.

2024-04-26 07:15 UTC, Leeyah-123 requested changes
The filter dropdown is not positioned well
![Uploading image.png…]()

2024-04-26 07:17 UTC, Leeyah-123 requested changes
Also, remove you're not passing the icon into the event card somewhere.
I think on the Browse page.

![image](https://github.com/Hemazyn/WillBeThere-RSVP/assets/101122860/ff3f2aa7-bba5-46ea-9c56-1f2c9b78d9a5)

2024-04-26 07:20 UTC, Leeyah-123 requested changes
These should be icons inside of buttons.
![image](https://github.com/Hemazyn/WillBeThere-RSVP/assets/101122860/a5198c1c-e764-4f97-b3a6-effa0d493213)

Also, the dropdowns are not accessible at all. Read up on accessible dropdowns and implement them. Both the event card dropdown and the filter dropdown.

2024-04-26 07:42 UTC, ezeaniiandrew commented
> These should be icons inside of buttons. ![image](https://private-user-images.githubusercontent.com/101122860/325883173-a5198c1c-e764-4f97-b3a6-effa0d493213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxMTczNzYsIm5iZiI6MTcxNDExNzA3NiwicGF0aCI6Ii8xMDExMjI4NjAvMzI1ODgzMTczLWE1MTk4YzFjLWU3NjQtNGY5Ny1iM2E2LWVmZmEwZDQ5MzIxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyNlQwNzM3NTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00OGM5NDgxMWJjYmU5OTBmOWU2ODk0ZjIwNThlODExNmRjMzYyZjAzNDNhYWQ3YzAxZjA3NmM1YzI5MmNjM2Y0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.bjmMogfXnguMT13DSkvC6paQOKdolMQh-xfI91WG5k4)
> 
> Also, the dropdowns are not accessible at all. Read up on accessible dropdowns and implement them. Both the event card dropdown and the filter dropdown.

I'll push a commit to fix the icon issue. Regarding accessibility, given the time constraints, I think it'll be better to implement that when we're done with the project so as not to delay the implementation of the important pages.

2024-04-26 09:01 UTC, Leeyah-123 approved these changes

2024-04-26 09:02 UTC, merged